package com.cesg;

import net.minecraft.resources.ResourceLocation;

public final class CESGIds {
    private CESGIds() {}

    public static ResourceLocation id(String path) {
        return ResourceLocation.fromNamespaceAndPath(CESG.MOD_ID, path);
    }

    /** Awarded in code by TeleportResolver (impossible trigger); generated by CESGAdvancementProvider. */
    public static final ResourceLocation GATEWAY_TRAVEL_ADVANCEMENT = id("gateway_travel");
    public static final String GATEWAY_TRAVEL_CRITERION = "traveled";
}
